### ISSUE TITLE
The examples are not working in ngx-quill 14.3.0.

### ISSUE THREAD

**Issue by zaoldyck** [KillerCodeMonkey/ngx-quill-example#898]
super(
      injector, elementRef, domSanitizer, platformId,
      renderer, zone, service
    )

It is working in ngx-quill 13.0.0 but not ngx-quill 14.3.0.
mat-quill-base.ts:error TS2554: Expected 8 arguments, but got 7.

**Comment by KillerCodeMonkey** [comment]
should be fixed.

i also rebuilt and deployed the demo page
